[package]
name = "eir"
version = "0.1.0"
authors = ["user01"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elfen = { git = "https://github.com/Project-Norn/elfen" }
x86asm = { git = "https://github.com/Project-Norn/x86asm" }
